# Generated by Django 4.0.5 on 2022-07-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='committee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=100)),
                ('cie1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cie2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cie3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name2', models.CharField(blank=True, max_length=100)),
                ('cieI', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cieII', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cieIII', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name3', models.CharField(blank=True, max_length=100)),
                ('ciei', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cieii', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cieiii', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name4', models.CharField(blank=True, max_length=100)),
                ('cie01', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cie02', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cie03', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name5', models.CharField(blank=True, max_length=100)),
                ('cie001', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cie002', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cie003', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('cie1', models.ImageField(upload_to='')),
                ('cie2', models.ImageField(blank=True, upload_to='')),
                ('cie3', models.ImageField(blank=True, upload_to='')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login2.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='committee',
            fields=[
                ('committee_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login2.course')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login2.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='admin1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login2.faculty')),
            ],
        ),
    ]
